// <auto-generated />
using System;
using ABPTestProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABPTestProject.Migrations
{
    [DbContext(typeof(AbptestTaskDbContext))]
    partial class AbptestTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ABPTestProject.Models.SiteVisitor", b =>
                {
                    b.Property<string>("DeviceToken")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Device_token");

                    b.Property<string>("ButtonColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Button_color");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.HasKey("DeviceToken")
                        .HasName("PK__SiteVisi__5A171AE3B633681C");

                    b.ToTable("SiteVisitors");
                });
#pragma warning restore 612, 618
        }
    }
}
